# persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-pv
  labels:
    type: worker
    app: hadoop
    hadoop: worker
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /opt/hadoop/hdfs/worker
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: hadoop
            operator: In
            values:
            - worker
---
# persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-pv-1
  labels:
    type: worker
    app: hadoop
    hadoop: worker
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /opt/hadoop/hdfs/worker
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: component
            operator: In
            values:
            - worker
---
# persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-pv-2
  labels:
    type: worker
    app: hadoop
    hadoop: worker
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /opt/hadoop/hdfs/worker
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: component
            operator: In
            values:
            - worker
---
# persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-pv-3
  labels:
    type: worker
    app: hadoop
    hadoop: worker
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /opt/hadoop/hdfs/worker
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: component
            operator: In
            values:
            - worker
---
# persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-pv-4
  labels:
    type: worker
    app: hadoop
    hadoop: worker
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /opt/hadoop/hdfs/worker
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: component
            operator: In
            values:
            - worker
---
# persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: worker-pv-claim
  labels: 
    app: hadoop
    hadoop: worker
spec:
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
