---
#datanode service
apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode-service
  namespace: hadoop
  labels:
    app: hadoop
    hadoop: datanode
spec:
  selector:
    hadoop: datanode
  ports: #Hadoop port
    - name: dn-rpc
      port: 80
      protocol: TCP
    - name: dn-web
      port: 50075
    - name: dn-web-ui
      port: 8042
    - name: ssh
      port: 22
---
# stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-datanode
  namespace: hadoop
  labels:
    app: hadoop
    hadoop: datanode
    hadoop: worker
spec:
  serviceName: hadoop-datanode-service
  replicas: 2 
  selector:
    matchLabels:
      hadoop: datanode
  template:
    metadata:
      namespace: hadoop
      labels:
        app: hadoop
        hadoop: datanode
    spec:
      containers:
        - name: hadoop-datanode
          #image: babbleshack/hadoop:datanode
          image: babbleshack/hadoop:worker
          imagePullPolicy: Always
          #volumeMounts:
          #  - name: datanode-pv-claim 
          #    mountPath: /opt/hadoop/hdfs/datanode
          ports:
            - name: dn-rpc
              containerPort: 80
            - name: dn-web
              containerPort: 50075
            - name: dn-web-ui
              containerPort: 8042
            - name: ssh
              containerPort: 22

#volumeClaimTemplates:
  #    - metadata:
    #     name: datanode-pv-claim
    # spec:
      #   accessModes:
        # - ReadWriteOnce
        #storageClassName: local-storage
        #resources:
          # requests:
            # storage: 5Gi
