---
#worker service
apiVersion: v1
kind: Service
metadata:
  name: hadoop-worker-service
  namespace: hadoop
  labels:
    app: hadoop
    hadoop: worker
spec:
  selector:
    hadoop: worker
  ports: #Hadoop port
    - name: dn-rpc
      port: 80
      protocol: TCP
    - name: dn-web
      port: 50075
    - name: dn-web-ui
      port: 8042
    - name: ssh
      port: 22
---
# stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-worker
  namespace: hadoop
  labels:
    app: hadoop
    hadoop: worker
    hadoop: worker
spec:
  serviceName: hadoop-worker-service
  replicas: 30 
  selector:
    matchLabels:
      hadoop: worker
  template:
    metadata:
      namespace: hadoop
      labels:
        app: hadoop
        hadoop: worker
    spec:
      containers:
        - name: hadoop-worker
          image: babbleshack/hadoop:base
          imagePullPolicy: Always
          command: [ "/bin/bash" ]
          args: [ "/opt/init_container.d/start_nodemanager.sh" ]
          ports:
            - name: dn-rpc
              containerPort: 80
            - name: dn-web
              containerPort: 50075
            - name: dn-web-ui
              containerPort: 8042
            - name: ssh
              containerPort: 22
