---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-master
  namespace: hdfs
  labels:
    app: hdfs
    hdfs: master
spec:
  serviceName: hdfs-master-service
  replicas: 1 
  selector:
    matchLabels:
      hdfs: master
  template: #pod template .spec.template
    metadata:
      namespace: hdfs
      labels:
        app: hdfs
        hdfs: master
    spec:
      hostname: hdfs-master-service
      containers:
        - name: hdfs-master
          #image: babbleshack/hdfs:master
          image: babbleshack/hdfs:base
          imagePullPolicy: Always
          command: [ "/bin/bash" ]
          args: [ "/opt/init_container.d/start_master.sh" ]
          ports:
            - name: nn
              containerPort: 8020
            - name: nn-rpc
              containerPort: 9000
            - name: nn-web
              containerPort: 50070
          env:
            - name: CLUSTER_NAME
              value: hdfs-k8s
