---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-master
  namespace: hadoop
  labels:
    app: hadoop
    hadoop: master
spec:
  serviceName: hadoop-master-service
  replicas: 1 
  selector:
    matchLabels:
      hadoop: master
  template: #pod template .spec.template
    metadata:
      namespace: hadoop
      labels:
        app: hadoop
        hadoop: master
    spec:
      hostname: hadoop-master-service
      containers:
        - name: hadoop-master
          #image: babbleshack/hadoop:master
          image: babbleshack/hadoop:base
          imagePullPolicy: Always
          command: [ "/bin/bash" ]
          args: [ "/opt/init_container.d/start_master.sh" ]
          volumeMounts:
            - name: master-pv-claim 
              mountPath: /hadoop/data
          ports:
            - name: nn-web
              containerPort: 50070
            - name: nn-rpc
              containerPort: 8020
            - name: rm
              containerPort: 8032
            - name: rm-admin
              containerPort: 8033
            - name: rm-admin-http
              containerPort: 8088
            - name: rm-sched
              containerPort: 8030
            - name: rt
              containerPort: 8031
            - name: nn-rpc-legacy
              containerPort: 9000
            - name: job-his-ui
              containerPort: 19888
            - name: job-his-rpc
              containerPort: 10020
          env:
            - name: CLUSTER_NAME
              value: hdfs-k8s
  volumeClaimTemplates: #volume claim .spec.volumeClaimTemplate
    - metadata:
        name: master-pv-claim
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: local-storage
        resources:
          requests:
            storage: 5Gi
