---
#namenode service
kind: Service
apiVersion: v1
metadata:
  name: hadoop-namenode-service
  namespace: hadoop
  labels:
    app: hadoop
    hadoop: namenode
spec:
  selector:
    hadoop: namenode
  ports: #Hadoop port http://fibrevillage.com/storage/637-hadoop-default-ports-reference
    - name: nn-rpc
      protocol: TCP
      port: 8020
    - name: nn-rpc-legacy
      protocol: TCP
      port: 9000
      #targetPort: 8020
    - name: nn-web #expose web interface on port 80 (9870->80)
      protocol: TCP
      port: 80
      targetPort: 50070
    - name: rm
      protocol: TCP
      port: 8032
    - name: rm-admin
      protocol: TCP
      port: 8033
    - name: rm-admin-http
      protocol: TCP
      port: 8088
    - name: rm-sched
      protocol: TCP
      port: 8030
    - name: rt
      protocol: TCP
      port: 8031
    - name: job-his-ui
      protocol: TCP
      port: 19888
    - name: job-his-rpc
      protocol: TCP
      port: 10020

