---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-namenode
  namespace: hadoop
  labels:
    app: hadoop
    hadoop: namenode
spec:
  serviceName: hadoop-namenode-service
  replicas: 1 
  selector:
    matchLabels:
      hadoop: namenode
  template: #pod template .spec.template
    metadata:
      namespace: hadoop
      labels:
        app: hadoop
        hadoop: namenode
    spec:
      hostname: hadoop-namenode-service
      containers:
        - name: hadoop-namenode
          #image: babbleshack/hadoop:namenode
          image: babbleshack/hadoop:base
          imagePullPolicy: Always
          command:
            - "/bin/bash"
            - "/opt/hadoop/bin/hdfs \"namenode -format\""
            - "/opt/hadoop/sbin/start-dfs.sh"
            - "/opt/hadoop/sbin/start-yarn.sh" 
            - "/bin/tail -F /opt/hadoop/logs/*"
          volumeMounts:
            - name: namenode-pv-claim 
              mountPath: /hadoop/data
          ports:
            - name: nn-web
              containerPort: 50070
            - name: nn-rpc
              containerPort: 8020
            - name: rm
              containerPort: 8032
            - name: rm-admin
              containerPort: 8033
            - name: rm-admin-http
              containerPort: 8088
            - name: rm-sched
              containerPort: 8030
            - name: rt
              containerPort: 8031
            - name: nn-rpc-legacy
              containerPort: 9000
            - name: job-his-ui
              containerPort: 19888
            - name: job-his-rpc
              containerPort: 10020
          env:
            - name: CLUSTER_NAME
              value: hdfs-k8s
  volumeClaimTemplates: #volume claim .spec.volumeClaimTemplate
    - metadata:
        name: namenode-pv-claim
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: local-storage
        resources:
          requests:
            storage: 5Gi
