#namenode service
kind: Service
apiVersion: v1
metadata:
  name: hadoop-namenode-service
  namespace: hadoop
  labels:
    app: hadoop
    hadoop: namenode
spec:
  selector:
    hadoop: namenode
  ports: #Hadoop port
    - name: nn-rpc
      protocol: TCP
      port: 8020
    - name: nn-rpc-legacy
      protocol: TCP
      port: 9000
      #targetPort: 8020
    - name: nn-web #expose web interface on port 80 (9870->80)
      protocol: TCP
      port: 80
      targetPort: 50070
---
# stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-namenode
  namespace: hadoop
  labels:
    app: hadoop
    hadoop: namenode
spec:
  serviceName: hadoop-namenode-service
  replicas: 1 
  selector:
    matchLabels:
      hadoop: namenode
  template: #pod template .spec.template
    metadata:
      namespace: hadoop
      labels:
        app: hadoop
        hadoop: namenode
    spec:
      hostname: hadoop-namenode-service
      containers:
        - name: hadoop-namenode
          image: babbleshack/hadoop:namenode
          imagePullPolicy: Always
          volumeMounts:
            - name: namenode-pv-claim 
              mountPath: /hadoop/data
          ports:
            - name: nn-web
              containerPort: 50070
            - name: nn-rpc
              containerPort: 8020
          env:
            - name: CLUSTER_NAME
              value: hdfs-k8s
  volumeClaimTemplates: #volume claim .spec.volumeClaimTemplate
    - metadata:
        name: namenode-pv-claim
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: local-storage
        resources:
          requests:
            storage: 5Gi
