---
# persistent volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: namenode-pv
  labels:
    app: hadoop
    type: namenode
    hadoop: namenode
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /opt/hadoop/hdfs/namenode
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: component
            operator: In
            values:
            - namenode
---
# persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: namenode-pv-claim
  labels:
    app: hadoop
    hadoop: namenode
spec:
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: local-storage
  resources:
    requests:
      storage: 4Gi
